name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal

    # nuget publish
    - name: Pack Localization
      run: dotnet pack src/Localization/Localization.csproj -c Release

    - name: Prep packages
      run: dotnet nuget add source --username valentaiga --password ${{ secrets.TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/valentaiga/index.json"

    - name: Publish to GitHub packages 
      run: dotnet nuget push Localization/Localization/bin/Release/*.nupkg --api-key ${{ secrets.TOKEN }}  --source "github"

